Query-parameter code verwijderd en verwijzing naar common op 1.3.0 gezet
VNG-Realisatie/Haal-Centraal-BRP-tabellen-bevragen pull request #16
Opened 2021-08-30 07:18 UTC by JohanBoer

N.a.v. #15

2021-08-30 07:58 UTC, MelvLee commented on specificatie/openapi.yaml
>        description: "Het ophalen van de tabelwaarden van een landelijke tabel.<br>Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. <br> Als de parameter <b> in
In de description staat nog dat met code kan worden gezocht. Ook is de code query parameter niet verwijderd uit de components/parameters

2021-08-30 07:59 UTC, MelvLee requested changes
zie opmerkingen

2021-09-01 10:48 UTC, KayodeBakker approved these changes

2021-09-02 07:15 UTC, MelvLee approved these changes

2021-09-22 14:57 UTC, melsk-r approved these changes

2021-09-23 08:00 UTC, merged